#lang racket
(require "../ast/nodes.rkt")
(define variable%
  (class object%
    (init-field name)
    (field [isRead #f] [isReadOutOfContext #f])
    (super-new)
    (abstract getReadNode read)
    (define/public (isAccessed) isRead)
    (define/public (isAccessedOutOfContext) isReadOutOfContext)
    (define/public (getSuperReadNode contextLevel holderClass classSide?)
      (set! isRead #t)
      (when (> contextLevel 0)
        (set! isReadOutOfContext #t))
      (if (equal? contextLevel 0)
          (LocalSuperReadNode holderClass classSide?)
          (NonLocalSuperReadNode contextLevel holderClass classSide?)))
    (define/public (getThisContextNode) (ThisContextNode 0))
    (define/public (isInternal) #f)))

(define argument%
  (class variable%
    (init-field index)
    (super-new [name name])
    (inherit-field name isRead isReadOutOfContext)
    (define/override (getReadNode contextLevel)
      ;(transferToInterpreterAndInvalidate)
      (set! isRead #t)
      (when (> contextLevel 0)
        (set! isReadOutOfContext #t))
      (if (equal? contextLevel 0)
          (LocalArgumentReadNode index)
          (NonLocalArgumentReadNode index contextLevel)))
    (define/override (read frame)
      (list-ref (send frame getArguments) index))))

(define local%
  (class variable%
    (init-field slot)
    (field [isWritten #f] [isWrittenOutOfContext #f])
    (super-new [name name])
    (inherit-field name isRead isReadOutOfContext)
    (define/public (getSlot) slot)
    (define/override (getReadNode contextLevel)
      ;(transferToInterpreterAndInvalidate)
      (set! isRead #t)
      (when (> contextLevel 0)
        (set! isReadOutOfContext #t))
      (UninitializedVariableReadNode this contextLevel))
    (define/public (getWriteNode contextLevel valueExpr)
      ;(transferToInterpreterAndInvalidate)
      (set! isWritten #t)
      (when (> contextLevel 0)
        (set! isWrittenOutOfContext #t))
      (UninitializedVariableWriteNode this contextLevel valueExpr))
    (define/override (read frame)
      (list-ref (send frame getValue) slot))
    (define/override (isAccessed) (or (super isAccessed) isWritten))
    (define/override (isAccessedOutOfContext) (or (super isAccessedOutOfContext) isWrittenOutOfContext))
    ))